url: http://another-example.com
items:
  - &x
    name: entity_x
    path: "body > div > p:nth-child(3) > a"
    primary: false
    item_type: Text
    related: []
  - &y
    name: entity_y
    path: "body > div > p:nth-child(3) > a"
    primary: false
    item_type: Text
    related:
      - *x
  - 
    name: entity_z
    path: "body > div > p:nth-child(3) > a"
    primary: true
    item_type: Text
    related:
      - *y